# lance bdd
# lance php (back)
# ./aafm-back:/???/symfony. 
# lance nginx (front)
# ./aafm-frot:/usr/aafm
#a copier a la racine du prog (qui dois contenir aafm-front + aafm-back)
version : '3.8'

services: 
  database:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: aafm-back
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  database-test:
    container_name: database-test
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: aafm-back-test
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4307:3306'
    volumes:
      - ./mysql-test:/var/lib/mysql
  php:
    container_name: php
    build:
      context: ./aafm-back
    ports:
      - "9000:9000"
    volumes:
      - ./aafm-back:/var/www/symfony_docker
    depends_on:
      - database
      - database-test
  nginx-back:
    container_name: nginx-back
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./aafm-back:/var/www/symfony_docker
      - ./aafm-back/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  nginx-front:
    container_name: nginx-front
    build:
      context: ./aafm-front
    ports:
      - "8081:80"
    volumes:
      - ./aafm-front:/var/www/aafm-front
      - ./aafm-front/nginx/default.conf:/etc/nginx/conf.d/default.
###> doctrine/doctrine-bundle ###
  # database:
  #   image: postgres:${POSTGRES_VERSION:-15}-alpine
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB:-app}
  #     # You should definitely change the password in production
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
  #     POSTGRES_USER: ${POSTGRES_USER:-app}
  #   volumes:
  #     - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
